disk_reader: !EasyReader &id_disk_reader
  args:
    dataset_name: mnli
    data_poison: True

dataset: !FastListDataset &id_dataset
  args:
    device: cuda:0
    batchsize: 2
    model_string: meta-llama/Llama-2-7b-hf
    seq_len: 256
  data_loader: *id_disk_reader
  prompt: True
  mapping: "{'entailment':'<Yes', 'neutral':'<Maybe', 'contradiction':'<No'}"
  template: "*<s>**sent_0*?*+sentl_1*Entailment_or_not*?*mask*sep+*"
  first_sent_limit: 200
  other_sent_limit: 40

probe_com: !NTKProbe &id_probe_com
  args:
    device: cuda:0
    seed: 2023
    dataset: mnli
    model: meta-llama/Llama-2-7b-hf
    datadir: ./datasets
    savedir: ./ntks
    logdir: null
    workers_per_device: 1
    grad_chunksize: 10000000 # adjust this value if memory is insufficient
    mm_col_chunksize: 20000
    loader_batch_size: 16  # adjust this value if memory is insufficient
    loader_num_workers: 1   # when memory is pinned, don't set this to non-zero values
    pin_memory: False # setting it to true will cause cpu to stuck at termination (might have a fix though)
    allow_tf32: False
    benchmark: False
    deterministic: True
    ntk_dtype: float32
    num_frozen_layers: 0
    debug: False
    prompt: True
    correction: False
    single_kernel: True
  num_labels: 3

dshap_com: !Fast_Data_Shapley
  dataset: *id_dataset
  probe_model: *id_probe_com
  num_metric: 2